apiVersion: v1
kind: ReplicationController
metadata:
  name: "{{.Values.Name}}"
  labels:
    k8s-app: {{.Values.Name}}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: {{default 1 .Values.replicaCount}}
  selector:
    k8s-app: "{{.Release.Name}}-{{.Values.Name}}"
  template:
    metadata:
      labels:
        k8s-app: "{{.Release.Name}}-{{.Values.Name}}"
    spec:
      containers:
      - name: {{.Values.Name}}
        image: "{{.Values.image.name}}:{{.Values.image.tag}}"
        env:
        - name: "ZK_HOSTS"
          value: {{.Values.zk.hosts}}
        ports:
        - containerPort: {{.Values.http.port}}

